struct stat;
struct rtcdate;

// system calls
int fork(void);
int exit(void) __attribute__((noreturn));
int wait(void);
int pipe(int*);
int write(int, const void*, int);
int read(int, void*, int);
int close(int);
int kill(int);
int exec(char*, char**);
int open(const char*, int);
int mknod(const char*, short, short);
int unlink(const char*);
int fstat(int fd, struct stat*);
int link(const char*, const char*);
int mkdir(const char*);
int chdir(const char*);
int dup(int);
int getpid(void);
char* sbrk(int);
int sleep(int);
int uptime(void);
int calculate_biggest_perfect_square(void);
void get_ancestors(void);
void set_sleep(int);
void set_date(struct rtcdate *);
void get_descendants(void);
int process_start_time(void);
void print_all_proc(void);
void set_queue(int, int);
void set_priority(int, int);
void set_bjf_params(int, int, int, int);
void multiple_acquire(int);
void rwtest(int);
void rw_exec(int);
void wr_exec(int);
void shm_getat(int);
void shm_detach(int);

// ulib.c
int stat(const char*, struct stat*);
char* strcpy(char*, const char*);
void *memmove(void*, const void*, int);
char* strchr(const char*, char c);
int strcmp(const char*, const char*);
void printf(int, const char*, ...);
char* gets(char*, int max);
uint strlen(const char*);
void* memset(void*, int, uint);
void* malloc(uint);
void free(void*);
int atoi(const char*);
